<a href="https://colab.research.google.com/github/nanunzoey/tensorflow_practice_using_python/blob/master/Practice_regression-classification_210527.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **레모네이드 판매 예측**

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 데이터 준비
from_file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
data = pd.read_csv(from_file)
data.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [5]:
# 종속, 독립변수 분리
val_independant = data[['온도']]
val_dependant = data[['판매량']]
print(val_independant.shape, val_dependant.shape)

(6, 1) (6, 1)


In [7]:
# 모델 만들기
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [15]:
# 모델 학습시키기
model.fit(val_independant, val_dependant, epochs=10, verbose=0)

In [16]:
# 모델 이용하기
model.predict(val_independant)

array([[39.98951 ],
       [41.989006],
       [43.988503],
       [45.988   ],
       [47.98749 ],
       [49.986988]], dtype=float32)

In [17]:
model.predict([[15]])

array([[29.99203]], dtype=float32)

### **보스턴 집값 예측**

In [2]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [4]:
# 1. 과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [8]:
# 독립, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [10]:
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [26]:
# 3. 모델을 학습(FIT)하기
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3082
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 24.2067
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 24.7417
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 23.8736
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 24.4499
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 24.0163
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 24.2537
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3988
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 24.5717
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3347


In [23]:
# 4. 모델을 이용하기
model.predict(독립[0:5])

array([[29.412807],
       [24.247135],
       [30.710491],
       [29.60601 ],
       [29.16743 ]], dtype=float32)

In [24]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [27]:
# 모델 수식 확인하기
model.get_weights()

[array([[-0.08954049],
        [ 0.05062823],
        [-0.0350601 ],
        [ 2.730693  ],
        [ 0.82633173],
        [ 5.306957  ],
        [-0.00988769],
        [-1.0029854 ],
        [ 0.18298551],
        [-0.00970421],
        [-0.43094265],
        [ 0.01440287],
        [-0.46408272]], dtype=float32), array([4.7828336], dtype=float32)]

### **아이리스 품종 분류**

In [28]:
# 라이브러리 가져오기
import pandas as pd
import tensorflow as tf

In [29]:
# 1. 과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [36]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [38]:
# 독립, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [39]:
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=(4))
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [46]:
# 3. 데이터로 모델을 학습(FIT)시키기
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.9467
Epoch 2/10
5/5 [==============================] - 0s 6ms/step - loss: 0.3518 - accuracy: 0.9533
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.3517 - accuracy: 0.9400
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.9533
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3497 - accuracy: 0.9533
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3492 - accuracy: 0.9533
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3497 - accuracy: 0.9533
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 0.3480 - accuracy: 0.9533
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.3477 - accuracy: 0.9533
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.3473 - accuracy: 0.9533


In [48]:
# 모델 이용하기
model.predict(독립[50:55])

array([[0.01665183, 0.6195605 , 0.3637877 ],
       [0.01867412, 0.54869056, 0.43263528],
       [0.0083281 , 0.5733691 , 0.41830286],
       [0.01186282, 0.52716964, 0.4609675 ],
       [0.00750068, 0.5291979 , 0.4633014 ]], dtype=float32)

In [49]:
print(종속[50:55])

    품종_setosa  품종_versicolor  품종_virginica
50          0              1             0
51          0              1             0
52          0              1             0
53          0              1             0
54          0              1             0


In [50]:
model.get_weights()

[array([[-0.04956865,  0.09698189, -0.0652703 ],
        [ 2.0276172 ,  0.2495866 , -0.07046593],
        [-1.5261892 , -0.02514214, -0.09655134],
        [-1.5156102 ,  0.00484622,  1.8365164 ]], dtype=float32),
 array([ 0.98269653,  0.07947084, -0.52175033], dtype=float32)]